name: Compile Sketches

on:
    - push
    
jobs:
    compile-sketch:
      runs-on: ubuntu-latest
  
      # Compile for Uno, Nano, Mega, and Uno R4 Wifi
      strategy:
        matrix:
          fqbn:
            - arduino:avr:uno
            - arduino:avr:nano
            - arduino:avr:mega
            - arduino:renesas_uno:unor4wifi
            
      steps:
        - uses: actions/checkout@v2
        - uses: arduino/compile-sketches@v1.1.0
          with:
            fqbn: ${{ matrix.fqbn }}
            sketch-paths: |
              - ./
            libraries: |
              - name: SD
              - name: OneWire
              - name: WindsOfChange
  