name: Lint

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v1
        with:
          project-type: library
          library-manager: submit
          compliance: specification
